using Microsoft.Graph;
using Microsoft.Graph.Auth;
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace Jeremy_sCuteTimeLoggingApp
{
    public partial class MainWindow : Window
    {
        //ListEntry selectedListEntry;
        public MainWindow()
        {
            InitializeComponent();
            DataContext = App.WorkEntryDataContext;
            
        }

        /// <summary>
        /// Call AcquireToken - to acquire a token requiring user to sign-in
        /// </summary>
        private void LoginButton_Click(object sender, RoutedEventArgs e)
        {
            App.WorkEntryDataContext.UpdateEventEntries();
            LoginButton.Visibility = Visibility.Collapsed;
            SignOutButton.Visibility = Visibility.Visible;
        }

        private void WorkEntryDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }

        private async void SignOutButton_Click(object sender, RoutedEventArgs e)
        {
            var accounts = await App.PublicClientApp.GetAccountsAsync();
            if (accounts.Any())
            {
                    await App.PublicClientApp.RemoveAsync(accounts.FirstOrDefault());
                    LoginButton.Visibility = Visibility.Visible;
                    SignOutButton.Visibility = Visibility.Collapsed;
            }
        }

        private void WorkEntryDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            try
            {
                App.WorkEntryDataContext.SelectedDataGridItem = (WorkEntry)e.AddedItems[0];
            }
            catch 
            {
                //TO-DO:Add Logging
            }
        }

        private void SaveEntryButton_Click(object sender, RoutedEventArgs e)
        {

        }

        private void LinkLabel_RequestNavigate(object sender, System.Windows.Navigation.RequestNavigateEventArgs e)
        {

        }
    }
}