using Microsoft.Graph;
using Microsoft.Graph.Auth;
using Microsoft.Identity.Client;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace Jeremy_sCuteTimeLoggingApp
{
    public partial class MainWindow : Window
    {

        public MainWindow()
        {
            InitializeComponent();
            DataContext = App.EventDataContext;
            
        }

        /// <summary>
        /// Call AcquireToken - to acquire a token requiring user to sign-in
        /// </summary>
        private void LoginButton_Click(object sender, RoutedEventArgs e)
        {
            App.EventDataContext.UpdateWorkEntries();
        }

        private void WorkEntryDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

        }

        private void WorkEntryDataGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            WorkEntry SelectedWorkEntry = (WorkEntry)e.AddedItems[0];
            TitleLabel.Content = SelectedWorkEntry.StartTimestamp.Date;
        }

    }
}